apiVersion: v1  
kind: Service  
metadata:  
  name: your-app-service  
spec:  
  type: ClusterIP # Change to LoadBalancer if you want external access  
  ports:  
    - port: 80  
      targetPort: 8080  
  selector:  
    app: your-app
